version: '3.8'
services:
  db:
    image: postgres:15
    container_name: finparse_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: finuser
      POSTGRES_PASSWORD: finpass
      POSTGRES_DB: finparse
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
